import { EventHandler } from "@create-figma-plugin/utilities";

export const COMMANDS = {
   FETCH_COLLECTION_CALL: "FETCH_COLLECTION_CALL",
   FETCH_COLLECTION_RESULT: "FETCH_COLLECTION_RESULT",
   MERGE_COLLECTIONS_CALL: "MERGE_COLLECTIONS_CALL",
   DUPLICATE_COLLECTION_CALL: "DUPLICATE_COLLECTION_CALL",
   DUPLICATE_COLLECTION_RESULT: "DUPLICATE_COLLECTION_RESULT",
   CHANGE_VARIABLE_LOCATION: "CHANGE_VARIABLE_LOCATION",
   GET_VARIABLE_INFO: "GET_VARIABLE_INFO",
   LET_USER_KNOW_ABOUT_DEPENDENCIES: "LET_USER_KNOW_ABOUT_DEPENDENCIES",
   UPDATE_VARIABLE_DEPENDENCIES: "UPDATE_VARIABLE_DEPENDENCIES",
   ERROR: "ERROR",
};
